version: '3.7'

services:
  mysqldb:
    image: mysql:9.0.1
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - ./db-data:/var/lib/mysql

  es-container:
    image: elasticsearch:8.15.1
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=123
      - xpack.security.enabled=false
    volumes:
      - ./es-data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.15.1
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
