version: '3.7'

services:
  mysqldb:
    image: mysql:9.0.1
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ~/.docker-conf/db-data:/var/lib/mysql

  es-container:
    image: elasticsearch:8.15.1
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=false
    volumes:
      - ~/.docker-conf/es-data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.15.1
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}

  rabbitmq:
    image: rabbitmq:4.0.0-rc.1-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq